name: mcp-us-airline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.26
  - pandas>=2.2
  - matplotlib>=3.8
  - seaborn>=0.13
  - networkx>=3.2
  - geopandas>=0.14
  - folium>=0.15
  - jupyter>=1.0
  - ipython>=8.21
  - scikit-learn>=1.4
  - pulp>=2.7
  - scipy>=1.12
  - pip>=24.0
