name: mcp-us-airline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - geopandas=0.14.4
  # - fiona>=1.9.5  # Added with exact version
  - seaborn
  - networkx
  - pandas
  - tqdm
  - rasterio
  - geopy
  - timezonefinder
  - pytz
  - jupyterlab
  - openpyxl
  - gdal
  - fa2
  - numba
  # Development dependencies
  - pytest
  - black
  - isort
  - flake8
  - pip